baseURL = "https://roveda.dev/"
languageCode = "pt-BR"
defaultContentLanguage = "pt"
title = "Mateus Roveda"
author = "Mateus Roveda"
theme = "vitae"
paginate = 5
enableRobotsTXT = true

copyright = "Â© Copyright | Mateus Roveda | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-186065365-1"

[taxonomies]
	tag = "tags"
	category = "categorias"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["roveeb","Mateus Roveda","roveda","tecnologia", "tutoriais"]

	# Add meta description in head part
	description = "Um pouco de tudo sobre tecnologia e outros trecos"

	# Add pagetitle to homepage <title> tag
	pagetitle = "Um pouco de tudo sobre tecnologia e outros trecos"

	# Add a subtitle to your website
	subtitle = "Um pouco de tudo sobre tecnologia e outros trecos"

	# Activate to show authors on pages if available
	listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	#avatar = "/img/me.jpg"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
    mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = true

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
engine = "disqus"

# Content types to disable comments on.
disableOnTypes = ["page"]

[params.comments.disqus]
shortname = "roveda" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Sobre"
url = "/page/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categorias"
url = "/categorias"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/mateusrovedaa"

[[params.social]]
name = "Youtube"
icon = "fab fa-youtube"
url = "https://youtube.com/ROVEEb"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/mateusrovedaa/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/mateusrovedaa"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
url = "mailto:mateus@roveda.dev"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

# Show raw HTML omitted
[markup.goldmark.renderer]
unsafe = true

# Related posts
[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categorias"
        weight = 100
	
	[[related.indices]]
        name = "tags"
        weight = 70